@startuml
skin rose
skinparam ActivityFontSize 15
skinparam ArrowFontSize 12
start
:User executes Filter Medium Priority command;

:Update FilteredPersonList by whether
the contact has a priority that is equal to med;
if (is FilteredPersonList empty?) then ([no])
    :Show the contacts with medium priority;
else ([yes])
    :Show CommandResult of no contacts found;
endif
stop
@enduml
